# Generated by Django 5.2.4 on 2025-08-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_college_customuser_index_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="accounts.department",
            ),
        ),
    ]
