# Generated by Django 5.2.4 on 2025-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="year_of_study",
            field=models.CharField(
                choices=[
                    ("100", "Level 100"),
                    ("200", "Level 200"),
                    ("300", "Level 300"),
                    ("400", "Level 400"),
                    ("500", "Level 500"),
                    ("600", "Level 600"),
                    ("700", "Level 700"),
                    ("800", "Level 800"),
                ]
            ),
        ),
    ]
