# Generated by Django 5.2.4 on 2025-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_customuser_year_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number for SMS notifications (include country code, e.g., +1234567890)",
                max_length=20,
                null=True,
            ),
        ),
    ]
