# Generated by Django 5.2.4 on 2025-09-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile image for the user",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
