# Generated by Django 5.2.4 on 2025-08-07 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aimy", "0002_chatsession_chatmessage_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="uud",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="uud",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="document",
            name="uud",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="documentchunk",
            name="uud",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="processingqueue",
            name="uud",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
