# Generated by Django 5.2.4 on 2025-08-07 22:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aimy", "0003_chatmessage_uud_chatsession_uud_document_uud_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenericFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="generic_files/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "docx",
                                    "txt",
                                    "md",
                                    "json",
                                    "csv",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word Document"),
                            ("txt", "Text File"),
                            ("md", "Markdown"),
                            ("json", "JSON"),
                            ("csv", "CSV"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_size", models.BigIntegerField(default=0)),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("is_processed", models.BooleanField(default=False)),
                ("processing_error", models.TextField(blank=True, null=True)),
                ("index_name", models.CharField(blank=True, max_length=255, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uud",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "verbose_name": "Generic File",
                "verbose_name_plural": "Generic Files",
                "db_table": "aimy_generic_file",
                "ordering": ["-created_at"],
            },
        ),
    ]
