# Generated by Django 5.2.4 on 2025-09-05 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aimy", "0005_genericfilechunk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title/description of the reminder",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of what to remind about",
                        null=True,
                    ),
                ),
                (
                    "original_message",
                    models.TextField(
                        help_text="Original user message that created this reminder"
                    ),
                ),
                (
                    "reminder_datetime",
                    models.DateTimeField(help_text="When to send the reminder"),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's timezone for the reminder",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("notification", "In-App Notification"),
                            ("email", "Email"),
                            ("both", "Both"),
                        ],
                        default="notification",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if reminder failed to send",
                        null=True,
                    ),
                ),
                (
                    "uud",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "chat_message",
                    models.ForeignKey(
                        help_text="Original chat message that triggered the reminder",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reminders",
                        to="aimy.chatmessage",
                    ),
                ),
                (
                    "chat_session",
                    models.ForeignKey(
                        help_text="Chat session where reminder was created",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="aimy.chatsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["reminder_datetime"],
                "indexes": [
                    models.Index(
                        fields=["status", "reminder_datetime"],
                        name="aimy_remind_status_b74e59_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="aimy_remind_user_id_91705d_idx"
                    ),
                ],
            },
        ),
    ]
