# Generated by Django 5.2.4 on 2025-09-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aimy", "0006_reminder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reminder",
            name="delivery_method",
            field=models.CharField(
                choices=[
                    ("notification", "In-App Notification"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("email_sms", "Email + SMS"),
                    ("all", "All Methods"),
                ],
                default="notification",
                max_length=20,
            ),
        ),
    ]
